# Generated by Django 3.2.9 on 2021-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='corpo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
